version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /tests
    schedule:
      interval: weekly
    groups:
      npm-test:
        dependency-type: development
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
